#!/usr/bin/env python3
"""Stage 1 / Step 1: broad U.S. market info rough filter.

This module owns the first mechanical gate in SignalForge:

1. Start from a broad U.S. market-info CSV, preferably the raw Nasdaq summary
   archive generated by ``nasdaq_summary_archive.py``.
2. Keep only rows with:
   - market cap >= $1B
   - price between $10 and $75, using ``previous_close`` as the price proxy
   - share volume >= 1,000,000
3. Write a deterministic rough-survivor CSV for the next Stage 1 step.

No premium, valuation, sentiment, or business-quality judgment belongs here.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from time import perf_counter
from typing import Iterable, Optional

DEFAULT_INPUT_CSV = "master_lists/nasdaq_summary_latest.csv"
DEFAULT_OUTPUT_CSV = "stages/stage1/output/stage1_step1_rough_filter.csv"
DEFAULT_MIN_MARKET_CAP = 1_000_000_000.0
DEFAULT_MIN_PRICE = 10.0
DEFAULT_MAX_PRICE = 75.0
DEFAULT_MIN_VOLUME = 1_000_000.0

OUTPUT_FIELDS = [
    "symbol",
    "name",
    "master_exchange",
    "sector",
    "industry",
    "price_proxy",
    "previous_close",
    "share_volume",
    "market_cap",
    "one_yr_target",
    "url",
    "json_path",
]


@dataclass(frozen=True)
class RoughFilterThresholds:
    min_market_cap: float = DEFAULT_MIN_MARKET_CAP
    min_price: float = DEFAULT_MIN_PRICE
    max_price: float = DEFAULT_MAX_PRICE
    min_volume: float = DEFAULT_MIN_VOLUME


@dataclass(frozen=True)
class RoughFilterResult:
    input_csv_path: str
    output_csv_path: str
    input_rows: int
    market_cap_survivors: int
    price_survivors: int
    volume_survivors: int
    missing_market_cap_rows: int
    missing_price_rows: int
    missing_volume_rows: int
    runtime_seconds: float


def parse_number(value: Optional[str]) -> Optional[float]:
    """Parse CSV numeric strings with commas/dollars into floats."""
    if value is None:
        return None
    text = str(value).replace(",", "").replace("$", "").strip()
    if not text or text.upper() in {"NA", "N/A", "NONE", "NULL", "-"}:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def row_price_proxy(row: dict[str, str]) -> Optional[float]:
    """Return the Stage 1 Step 1 price proxy.

    Nasdaq summary archive rows do not contain a dedicated live price field, so
    ``previous_close`` is the canonical proxy. If a future source adds ``price``
    or ``lastsale``, support it without changing the Stage 1 contract.
    """
    for field in ("price_proxy", "previous_close", "price", "lastsale"):
        price = parse_number(row.get(field))
        if price is not None:
            return price
    return None


def row_passes_market_cap(row: dict[str, str], thresholds: RoughFilterThresholds) -> bool:
    market_cap = parse_number(row.get("market_cap") or row.get("marketCap"))
    return market_cap is not None and market_cap >= thresholds.min_market_cap


def row_passes_price(row: dict[str, str], thresholds: RoughFilterThresholds) -> bool:
    price = row_price_proxy(row)
    return price is not None and thresholds.min_price <= price <= thresholds.max_price


def row_passes_volume(row: dict[str, str], thresholds: RoughFilterThresholds) -> bool:
    volume = parse_number(row.get("share_volume") or row.get("ShareVolume") or row.get("volume"))
    return volume is not None and volume >= thresholds.min_volume


def normalize_output_row(row: dict[str, str]) -> dict[str, str]:
    price_proxy = row_price_proxy(row)
    return {
        "symbol": (row.get("symbol") or "").strip().upper(),
        "name": (row.get("name") or "").strip(),
        "master_exchange": (row.get("master_exchange") or row.get("exchange") or row.get("api_exchange") or "").strip(),
        "sector": (row.get("sector") or "").strip(),
        "industry": (row.get("industry") or "").strip(),
        "price_proxy": "" if price_proxy is None else str(price_proxy),
        "previous_close": str(parse_number(row.get("previous_close")) or ""),
        "share_volume": str(parse_number(row.get("share_volume")) or ""),
        "market_cap": str(parse_number(row.get("market_cap") or row.get("marketCap")) or ""),
        "one_yr_target": str(parse_number(row.get("one_yr_target")) or ""),
        "url": (row.get("url") or "").strip(),
        "json_path": (row.get("json_path") or "").strip(),
    }


def apply_rough_filter(
    rows: Iterable[dict[str, str]],
    thresholds: RoughFilterThresholds = RoughFilterThresholds(),
) -> tuple[list[dict[str, str]], dict[str, int]]:
    input_rows = list(rows)
    market_cap_rows: list[dict[str, str]] = []
    price_rows: list[dict[str, str]] = []
    volume_rows: list[dict[str, str]] = []

    missing_market_cap_rows = 0
    missing_price_rows = 0
    missing_volume_rows = 0

    for row in input_rows:
        if parse_number(row.get("market_cap") or row.get("marketCap")) is None:
            missing_market_cap_rows += 1
        if not row_passes_market_cap(row, thresholds):
            continue
        market_cap_rows.append(row)

        if row_price_proxy(row) is None:
            missing_price_rows += 1
        if not row_passes_price(row, thresholds):
            continue
        price_rows.append(row)

        if parse_number(row.get("share_volume") or row.get("ShareVolume") or row.get("volume")) is None:
            missing_volume_rows += 1
        if not row_passes_volume(row, thresholds):
            continue
        volume_rows.append(row)

    survivors = [normalize_output_row(row) for row in volume_rows]
    survivors.sort(key=lambda row: (row["symbol"]))
    stats = {
        "input_rows": len(input_rows),
        "market_cap_survivors": len(market_cap_rows),
        "price_survivors": len(price_rows),
        "volume_survivors": len(survivors),
        "missing_market_cap_rows": missing_market_cap_rows,
        "missing_price_rows": missing_price_rows,
        "missing_volume_rows": missing_volume_rows,
    }
    return survivors, stats


def run_stage1_step1_rough_filter(
    *,
    input_csv_path: str = DEFAULT_INPUT_CSV,
    output_csv_path: str = DEFAULT_OUTPUT_CSV,
    thresholds: RoughFilterThresholds = RoughFilterThresholds(),
) -> RoughFilterResult:
    started_at = perf_counter()
    input_path = Path(input_csv_path).expanduser()
    output_path = Path(output_csv_path).expanduser()

    with input_path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))

    survivors, stats = apply_rough_filter(rows, thresholds)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(survivors)

    return RoughFilterResult(
        input_csv_path=str(input_path),
        output_csv_path=str(output_path),
        input_rows=stats["input_rows"],
        market_cap_survivors=stats["market_cap_survivors"],
        price_survivors=stats["price_survivors"],
        volume_survivors=stats["volume_survivors"],
        missing_market_cap_rows=stats["missing_market_cap_rows"],
        missing_price_rows=stats["missing_price_rows"],
        missing_volume_rows=stats["missing_volume_rows"],
        runtime_seconds=perf_counter() - started_at,
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Stage 1 Step 1 rough U.S. market filter")
    parser.add_argument("--input-csv", default=DEFAULT_INPUT_CSV, help="Raw Nasdaq summary CSV to filter")
    parser.add_argument("--output-csv", default=DEFAULT_OUTPUT_CSV, help="Rough survivor CSV to write")
    parser.add_argument("--min-market-cap", type=float, default=DEFAULT_MIN_MARKET_CAP)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--max-price", type=float, default=DEFAULT_MAX_PRICE)
    parser.add_argument("--min-volume", type=float, default=DEFAULT_MIN_VOLUME)
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    result = run_stage1_step1_rough_filter(
        input_csv_path=args.input_csv,
        output_csv_path=args.output_csv,
        thresholds=RoughFilterThresholds(
            min_market_cap=args.min_market_cap,
            min_price=args.min_price,
            max_price=args.max_price,
            min_volume=args.min_volume,
        ),
    )
    print("Stage 1 Step 1 rough filter complete")
    print(f"- Input rows: {result.input_rows}")
    print(f"- Market-cap survivors: {result.market_cap_survivors}")
    print(f"- Price survivors: {result.price_survivors}")
    print(f"- Volume survivors: {result.volume_survivors}")
    print(f"- Output CSV: {result.output_csv_path}")
    print(f"- Runtime seconds: {result.runtime_seconds:.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
